# Generated by Django 5.0.1 on 2024-08-03 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product name")),
                ("description", models.TextField(verbose_name="Product description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Product price"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=80, unique=True, verbose_name="Product slug"
                    ),
                ),
                (
                    "discount",
                    models.SmallIntegerField(
                        default=0, verbose_name="Product discount"
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Product archived"),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Product available"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Product updated at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Product created at"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantity of product"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Product created by",
                    ),
                ),
            ],
        ),
    ]
