# Generated by Django 5.0.1 on 2024-08-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Category name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Category description"),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=models.CharField(
                            max_length=80, verbose_name="Category name"
                        ),
                        max_length=80,
                        unique=True,
                        verbose_name="Category slug",
                    ),
                ),
                (
                    "category_image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Category image",
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                        verbose_name="Category parent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="Product category",
            ),
        ),
    ]
