# Generated by Django 5.0.1 on 2024-08-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_remove_cart_product"),
        ("products", "0003_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="products.product",
                verbose_name="Product",
            ),
        ),
    ]
