# Generated by Django 5.0.1 on 2024-08-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
