# Generated by Django 5.0.1 on 2024-02-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadToCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='categories/')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='categories/<django.db.models.fields.CharField>', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/<django.db.models.fields.CharField>', verbose_name='Image'),
        ),
    ]
